Fix/remove all shipping
Prospress/automatewoo-subscriptions pull request #46
Opened 2020-05-14 10:07 UTC by layoutd

Fixes #45 

Selecting "All shipping methods" in the _Subscription - Remove Shipping_ action didn't actually remove anything from the subscription. The problem was that the workflow was saving the `shipping_method_id` as `all`, and then comparing each individual shipping method in the subscription against that ID (so no single shipping method matched the ID).

I added the condition that removes each shipping method if the ID matches the one provided in the workflow, _or_ if the ID in the workflow is `all`. 

### Detailed test instructions:
- Create a subscription with one or more shipping line items.
- Create a workflow with the action Subscription → Remove Shipping and choose the "All shipping methods" option (recommend trigger Subscriptions → Subscription Note Added).
- Trigger the workflow and confirm that all the shipping methods were properly removed from the subscription.
- Confirm that the "Shipping Method ID" in the note added to the subscription by the workflow isn't `0` (should be something like `flat_rate` or `free_shipping`).

2020-05-18 00:51 UTC, jconroy commented
@JPry just assigned you to this one to get it on your radar

2020-05-19 21:08 UTC, JPry requested changes
Looks good, just some minor formatting issues to address.

2020-05-19 21:08 UTC, JPry commented on includes/abstracts/actions/edit-shipping.php
> +			$shipping_method_titles[$this->all_shipping_method_option_key] = __( 'All shipping methods', 'automatewoo-subscriptions' );
Minor: This needs spaces around variable in the array access.

```suggestion
			$shipping_method_titles[ $this->all_shipping_method_option_key ] = __( 'All shipping methods', 'automatewoo-subscriptions' );
```

2020-05-19 21:08 UTC, JPry commented on includes/actions/remove-shipping.php
> +			if ( 0 === strpos( $line_item->get_method_id(), $shipping_data['shipping_method_id'] )
Minor: If we're going to split the `if` statement across multiple lines, then the first condition should be on its own line.

2020-05-29 16:12 UTC, JPry approved these changes
LGTM 👍

2020-06-01 11:32 UTC, merged